### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by ghost** [hq9000/cython-vst-loader#10]
Hi hq9000,

this looks like a project I was searching for ;-)
Do you already support Windows? I would be open to test it.

Thanks!

**Comment by hq9000** [comment]
added a reply to a related SO question:
https://stackoverflow.com/questions/66361882/cython-vst-loader-not-installing-through-pip

**Comment by ghost** [comment]
Hi hq9000,
thanks for the reply. I tried before a bit to work around this but ended up at some of the linux specific commands.
Thus I chose to work with another package to host VST instruments

**Comment by hq9000** [comment]
![image](https://user-images.githubusercontent.com/21345604/111060267-9db41c00-84ac-11eb-8d14-bc7fb1f0f484.png)

**Comment by hq9000** [comment]
![image](https://user-images.githubusercontent.com/21345604/111060356-61cd8680-84ad-11eb-997a-0044763fd7d9.png)

**Comment by hq9000** [comment]
![image](https://user-images.githubusercontent.com/21345604/111111530-8d18aa00-856f-11eb-8e38-bc0663368cc2.png)

**Comment by hq9000** [comment]
![image](https://user-images.githubusercontent.com/21345604/111112444-3b711f00-8571-11eb-9ed9-b7988559cd35.png)

**Comment by hq9000** [comment]
![image](https://user-images.githubusercontent.com/21345604/111187564-2920d080-85c5-11eb-9f22-93610d6cfe3f.png)

**Comment by hq9000** [comment]
I guess there is some stupid pointer-related bug that makes

- [ ] synth1 constantly crash on the second process replacing with non-empty event list (only in float case, double replacing works fine)
- [ ] TyrellN6 randomly crash

too bad none of the open source plugins in test crash as of now

**Comment by hq9000** [comment]
## TyrellN6 crashes, available debugginng info:

crashing both in processing and double mode

below screenshots are for float processing case:

![image](https://user-images.githubusercontent.com/21345604/111433575-7f018f80-870f-11eb-9977-086fc2590e00.png)
![image](https://user-images.githubusercontent.com/21345604/111433869-e0c1f980-870f-11eb-8787-aef39ac4b7eb.png)
![image](https://user-images.githubusercontent.com/21345604/111434128-3ac2bf00-8710-11eb-9593-cb77ddde77f5.png)

**Comment by hq9000** [comment]
## Synth1 crashes

(weirdly, it works okay if instead of processing, double processing is used)

![image](https://user-images.githubusercontent.com/21345604/111434314-7493c580-8710-11eb-93d6-aa4faee22a4d.png)
![image](https://user-images.githubusercontent.com/21345604/111434442-9b51fc00-8710-11eb-812c-865eec88ef62.png)

**Comment by hq9000** [comment]
Tyrel N6 crash, double replacing, something is wrong with opcode 13?

![image](https://user-images.githubusercontent.com/21345604/111435303-abb6a680-8711-11eb-8d04-9c63c942d83f.png)

**Comment by hq9000** [comment]
![image](https://user-images.githubusercontent.com/21345604/111587007-aff6c880-87d2-11eb-81ec-25e451b6e20d.png)

**Comment by hq9000** [comment]
https://stackoverflow.com/questions/23178606/debugging-python-fatal-error-gc-object-already-tracked

**Comment by hq9000** [comment]
some OS synths for debugging:

https://github.com/reales/OB-Xd

**Comment by hq9000** [comment]
![image](https://user-images.githubusercontent.com/21345604/111866019-71e8d880-897b-11eb-8870-91319cbbdaa4.png)

**Comment by hq9000** [comment]
- [x] test releasing through test pypi through a randomized tag (in `release` job)
- [x] manually test installing from test pypi on linux and windows (py37)
- [x] add test in windows using Dragonfly reverb
- [ ] update readme
  - state project goals 
- [x] add linting test 
- [ ] adjust workflow (without publishing in pypi) to be triggered by master pushes and PR-to-master pushes
- [ ] make workflow additionally publish to pypi if something is tagged with `vX.Y.Z` tag

**Comment by ghost** [comment]
Hi hq9000,
does this mean, you have a working version for windows? I could also test with some VSTs I have

**Comment by hq9000** [comment]
@dimentorium 

hi! not yet, but it's getting close to.

need to adjust a few things, but generally i saw it working with some open source vst2 synths, namelly: OB-Xd, tunefish

weirdly, synth1 i couldn't get working, it mysteriously crashes and I  cannot debug it (no source code). Tyrell N6 also crashes, but for different reasons, it seems to require multiple threads to work and that doesn't seem to play well with python.

there will be a list of "officially" supported plugins in readme.

**Comment by hq9000** [comment]
![create_release_github](https://user-images.githubusercontent.com/21345604/112721460-ea6c0e00-8f14-11eb-829d-e2ee3f3906b9.gif)
